name: Build Flet EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install flet
        run: pip install flet --upgrade
      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build EXE with Flet
        run: flet pack src/main.py --icon src/assets/icon.png --add-data "src/assets;assets"

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickDNSChanger-Windows
          path: dist/main.exe
