name: Build Flet App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet (Latest Version)
        run: pip install --upgrade flet

      - name: Build Flet app
        run: flet build windows src/main.py --assets src/assets --no-flutter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-windows-app
          path: build/windows/runner/Release/
